test_task:
  matrix:
    - container:
        image: rust:latest
    - allow_failures: true
      container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

freebsd_test_task:
  name: cargo test (stable)
  matrix:
    - freebsd_instance:
        image_family: freebsd-13-0-snap
  env:
    HOME: /tmp # cargo needs it
  install_script: pkg install -y rust
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --all
  test_script: cargo test --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
