[package]
name = "userland"
version = "0.1.0"
authors = ["Till Wegmueller <toasterson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
pest_derive = "2.1.0"
maplit = "0.1.6"
pest = "2.1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
semver = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"